sudo: false
language: node_js
node_js:
- stable
- '9'
- '8'
- '7'
cache:
  directories:
    - "node_modules"
deploy:
  provider: npm
  email: findamir@gmail.com
  api_key:
    secure: g34n9TFa2hwxN8AN+8JP2jVz99YDeHtL5yOsMoAhq1o6QTAZGG4yKUYAkK4fGxyDUX1Rxe+4qOuvH7cbgNG/yjpPDscKWmhLL81qjpCP36u98VBK+MIeFgfKH3YQRKSiK9rhlF90j2LR96T1FqVLlu30Kzo5pHFFkxamVajt2uU=
  on:
    tags: true
    repo: amir20/phantomjs-node
before_script:
  - npm install -g gulp-cli
before_install:
- npm install -g codecov
after_success:
- codecov
